### ISSUE TITLE
寻找高清播放地址

### ISSUE THREAD

**Issue by Lawrence-Liu** [fly2tomato/dn-get#2]
我有多瑙会员，我想找到从低清视频地址到高清视频地址的转换规则，能问一下你是怎么找到之前的转换规则的吗？

**Comment by fly2tomato** [comment]
现在新服务器已经改规则了，要重新抓包分析，如果你愿意提供vip账号，我还可以接着更新软件~

**Comment by ffall007** [comment]
你好，我今天研究了一下多瑙影院的视频地址解析，看到了你Hexo上的文章，几经周折总算在这里找到你。首先想告诉你多瑙的Cookie非常无脑，不加密地保存了用户的密码，所以你的帐号密码在你的截图里暴露了...你处理一下吧。

另外最近多瑙似乎加强了加密措施，HTML里能看到的key不再是最终发送的key了，应该是被“http://static.dnvod.tv/js/2016/playerselection-1.2.7.72.js”里的某些函数处理过。这个脚本被加密过，语句本身可以被解密但是变量名不行所以很难读。而且即便这个问题可以解决，我发现“GetResource.ashx”返回的mp4地址变成了一个rtmp协议的地址、似乎也不能直接拿来播放了。

**Comment by ffall007** [comment]
你好，我今天研究了一下多瑙影院的视频地址解析，看到了你Hexo上的文章，几经周折总算在这里找到你。首先想告诉你多瑙的Cookie非常无脑，不加密地保存了用户的密码，所以你的帐号密码在你的截图里暴露了...你处理一下吧。

另外最近多瑙似乎加强了加密措施，HTML里能看到的key不再是最终发送的key了，应该是被”static.dnvod.tv/js/2016/playerselection-1.2.7.72.js”里的某些函数处理过。这个脚本被加密过，语句本身可以被解密但是变量名不行所以很难读。而且即便这个问题可以解决，我发现“GetResource.ashx”返回的mp4地址变成了一个rtmp协议的地址、似乎也不能直接拿来播放了。
